language: elixir
elixir: 1.2.2
otp_release:
  - 18.2.1
sudo: false
before_script:
  - mix deps.get
script:
  - mix compile
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report